# Generated by Django 4.0.4 on 2022-05-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='lat_long',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
