# Generated by Django 4.0.4 on 2022-05-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinic_lat_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='image',
            field=models.ImageField(null=True, upload_to='clinic_photo'),
        ),
    ]
