# Generated by Django 4.0.4 on 2022-05-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_clinic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='end_day',
            field=models.CharField(choices=[('Пн', 'Понедельник'), ('Вт', 'Вторник'), ('Ср', 'Среда'), ('Чт', 'Четверг'), ('Пт', 'Пятница'), ('Сб', 'Суббота'), ('Вс', 'Суббота')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='start_day',
            field=models.CharField(choices=[('Пн', 'Понедельник'), ('Вт', 'Вторник'), ('Ср', 'Среда'), ('Чт', 'Четверг'), ('Пт', 'Пятница'), ('Сб', 'Суббота'), ('Вс', 'Суббота')], max_length=25, null=True),
        ),
    ]
