# Generated by Django 4.0.4 on 2022-05-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_clinic_end_day_clinic_start_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='end_day',
            field=models.CharField(choices=[('Пн', 'Понедельник'), ('Вт', 'Вторник'), ('Ср', 'Среда'), ('Чт', 'Четверг'), ('Пт', 'Пятница'), ('Сб', 'Суббота'), ('Вс', 'Воскресенье')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='start_day',
            field=models.CharField(choices=[('Пн', 'Понедельник'), ('Вт', 'Вторник'), ('Ср', 'Среда'), ('Чт', 'Четверг'), ('Пт', 'Пятница'), ('Сб', 'Суббота'), ('Вс', 'Воскресенье')], max_length=25, null=True),
        ),
    ]
