# Generated by Django 4.0.4 on 2022-04-29 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0001_initial'),
        ('clinics', '0001_initial'),
        ('services', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialists.specialist')),
            ],
        ),
    ]
