# Generated by Django 4.0.4 on 2022-04-30 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('appointments', '0005_alter_appointment_service'),
        ('specialists', '0005_alter_specialist_education'),
        ('services', '0004_clinicservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='desc',
            field=models.TextField(default='ddff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='specialist',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='specialists.specialist'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ClinicService',
        ),
    ]
