# Generated by Django 4.0.4 on 2022-04-30 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0002_specialist_experience_specialist_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=500, null=True)),
                ('speciality', models.CharField(max_length=500, null=True)),
                ('finished', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='specialist',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specialists.education'),
        ),
    ]
