# Generated by Django 4.0.4 on 2022-04-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0003_education_specialist_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='education',
        ),
        migrations.AddField(
            model_name='specialist',
            name='education',
            field=models.ManyToManyField(null=True, to='specialists.education'),
        ),
    ]
