# Generated by Django 4.0.4 on 2022-04-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0004_remove_specialist_education_specialist_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='education',
            field=models.ManyToManyField(to='specialists.education'),
        ),
    ]
